### ISSUE TITLE
NAN or INF in Final LOSS

### ISSUE THREAD

**Issue by Vaheed1990** [nabsabraham/focal-tversky-unet#10]
Hi there,
Thanks for sharing your code. I tried to apply your code to my datasets. However, I got very weird loss values (inf or nan). I used attn_reg model and apply focal loss for first three outputs and tversky_loss for final output. I am wondering to know that how can I resolve this issue. I checked my data and try to add gradient clipping to prevent the exploding gradient problem. But, non of them did not work out.

**Comment by jiejiangd** [comment]
Hi there,
I try to reproduce your article and use the code intact, but the experimental results are quite different from the experimental results in the paper.I would like to ask if you have a complete implementation of this article, can you give some help?

model:attn_reg,loss:focal_tversky
my results:
DSC 0.748
Precision 0.860
Recall 0.752
results in article:
DSC 0.804
Precision 0.829
Recall 0.817
Hope to get your help! thanks!

**Comment by xiongjhang** [comment]
Hi, did you solve this problem?
