### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by DanielLee343** [nabsabraham/focal-tversky-unet#14]
Hi, hope you see this. Which version of  TensorFlow and python did you use to train the model, 'cause my version fails to execute the following code:
`precision, recall, thresholds = precision_recall_curve(y_true, y_preds)`    in training isic dataset.
Guess it might be some version issues. Thanks!

**Comment by nabsabraham** [comment]
Hi Daniel! I believe it was tf 1.0.1

**Comment by Halleyawoo** [comment]
> Hi, hope you see this. Which version of TensorFlow and python did you use to train the model, 'cause my version fails to execute the following code:
> `precision, recall, thresholds = precision_recall_curve(y_true, y_preds)` in training isic dataset.
> Guess it might be some version issues. Thanks!

Hello, have you solved this problem？

**Comment by DanielLee343** [comment]
Yes. My configuration is tensorflow-gpu = 1.13.1, keras = 2.3.1, cuda = 10.1 and it works fine then.

**Comment by Halleyawoo** [comment]
> Yes. My configuration is tensorflow-gpu = 1.13.1, keras = 2.3.1, cuda = 10.1 and it works fine then.

博主你好，我的版本是tensorflow-gpu = 1.0.1, keras = 2.0.2, cuda = 8.0，不知道是不是要全部和你改成一样的，方便的话可以展示一下最后的结果图吗（就是代码最后#plot precision-recall 这里的）？

**Comment by Halleyawoo** [comment]
> Yes. My configuration is tensorflow-gpu = 1.13.1, keras = 2.3.1, cuda = 10.1 and it works fine then.

谢谢你的回答

**Comment by DanielLee343** [comment]
最好改成一样的吧，改一下很容易，不然到时候出bug都不知道是哪里出错

**Comment by Halleyawoo** [comment]
> 最好改成一样的吧，改一下很容易，不然到时候出bug都不知道是哪里出错

好的，多谢回答。

**Comment by Halleyawoo** [comment]
大佬，请问那个分割结果的可视化你做了吗，怎么实现呢
