### ISSUE TITLE
Is upsample_g an upsampled version of g?

### ISSUE THREAD

**Issue by phernst** [nabsabraham/focal-tversky-unet#2]
From newmodels.AttnGatingBlock:
https://github.com/nabsabraham/focal-tversky-unet/blob/2c6ad9535bf6d1bc73371b0f6a57f7daf0af458e/newmodels.py#L86-L93

- `theta_x` is half the (spatial) size of `x` (due to the strided conv)
- `g` (as well as `phi_g`) is half the (spatial) size of `x` (due to max pooling in the unet)

So `upsample_g` is also half the (spatial) size of `x` and there is no need to calculate the strides in Conv2DTranspose since it will always be 1, or am I missing something?

The `2x UP` step on `x_l` in Fig. 3 of your paper should be `2x DOWN` then, right?

**Comment by nabsabraham** [comment]
hi @phernst! sorry about the super late reply! yes you are correct, the diagram is wrong but the code is correct. I will update this repo soon :)
