### ISSUE TITLE
about Conv2DTranspose

### ISSUE THREAD

**Issue by xiewenxin** [nabsabraham/focal-tversky-unet#4]
hi，your code and paper is  help me a lot. and thanks for you open source your code. i have question about your  Conv2DTranspose . in your paper  Fig2 
![image](https://user-images.githubusercontent.com/31923425/59580901-81335600-9105-11e9-8312-8e2ccc16e56f.png)
you concatenate two input,then use 3x3 conv + bn + relu ,and use  upconv(you use Conv2DTranspose in code). but in your code , you did'nt use  (3x3 conv + bn + relu)  after concatenate,and  you use it in output. is it the same?

**Comment by nabsabraham** [comment]
hi xiewenxin! I guess this is a diagram issue - I meant to use a different colour for just "do nothing" step but  the diagram became to colorful. The code is correct and I did not do conv x relu x bn after the concat but you can if you have gpu space!
